// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\task\{task_id}\field\{field_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithField_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithField_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/task/{task_id}/field/{field_id}{?custom_task_ids*,team_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithField_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/task/{task_id}/field/{field_id}{?custom_task_ids*,team_id*}", rawUrl)
        {
        }
        /// <summary>
        /// Remove the data from a Custom Field on a task. This does not delete the option from the Custom Field.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_DeleteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_DeleteResponse?> DeleteAsWithField_DeleteResponseAsync(Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_ItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_DeleteResponse> DeleteAsWithField_DeleteResponseAsync(Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_ItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_DeleteResponse>(requestInfo, global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_DeleteResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Remove the data from a Custom Field on a task. This does not delete the option from the Custom Field.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use DeleteAsWithField_DeleteResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_Response?> DeleteAsync(Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_ItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_Response> DeleteAsync(Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_ItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_Response>(requestInfo, global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Add data to a Custom field on a task. \ \You&apos;ll need to know the `task_id` of the task you want to update, and the universal unique identifier (UUID) `field_id` of the Custom Field you want to set. \ \You can use [Get Accessible Custom Fields](ref:getaccessiblecustomfields) or the [Get Task](ref:gettask) endpoint to find the `field_id`.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostResponse?> PostAsWithField_PostResponseAsync(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_PostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_ItemRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostResponse> PostAsWithField_PostResponseAsync(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_PostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_ItemRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostResponse>(requestInfo, global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Add data to a Custom field on a task. \ \You&apos;ll need to know the `task_id` of the task you want to update, and the universal unique identifier (UUID) `field_id` of the Custom Field you want to set. \ \You can use [Get Accessible Custom Fields](ref:getaccessiblecustomfields) or the [Get Task](ref:gettask) endpoint to find the `field_id`.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsWithField_PostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_Response?> PostAsync(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_PostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_ItemRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_Response> PostAsync(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_PostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_ItemRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_Response>(requestInfo, global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Remove the data from a Custom Field on a task. This does not delete the option from the Custom Field.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_ItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_ItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Add data to a Custom field on a task. \ \You&apos;ll need to know the `task_id` of the task you want to update, and the universal unique identifier (UUID) `field_id` of the Custom Field you want to set. \ \You can use [Get Accessible Custom Fields](ref:getaccessiblecustomfields) or the [Get Task](ref:gettask) endpoint to find the `field_id`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_PostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_ItemRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_PostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_ItemRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Remove the data from a Custom Field on a task. This does not delete the option from the Custom Field.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithField_ItemRequestBuilderDeleteQueryParameters 
        {
            /// <summary>If you want to reference a task by it&apos;s custom task id, this value must be `true`.</summary>
            [QueryParameter("custom_task_ids")]
            public bool? CustomTaskIds { get; set; }
            /// <summary>When the `custom_task_ids` parameter is set to `true`, the Workspace ID must be provided using the `team_id` parameter. \For example: `custom_task_ids=true&amp;team_id=123`.</summary>
            [QueryParameter("team_id")]
            public double? TeamId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithField_ItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_ItemRequestBuilderDeleteQueryParameters>
        {
        }
        /// <summary>
        /// Add data to a Custom field on a task. \ \You&apos;ll need to know the `task_id` of the task you want to update, and the universal unique identifier (UUID) `field_id` of the Custom Field you want to set. \ \You can use [Get Accessible Custom Fields](ref:getaccessiblecustomfields) or the [Get Task](ref:gettask) endpoint to find the `field_id`.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithField_ItemRequestBuilderPostQueryParameters 
        {
            /// <summary>If you want to reference a task by its Custom Task ID, this value must be `true`.</summary>
            [QueryParameter("custom_task_ids")]
            public bool? CustomTaskIds { get; set; }
            /// <summary>When the `custom_task_ids` parameter is set to `true`, the Workspace ID must be provided using the `team_id` parameter. \For example: `custom_task_ids=true&amp;team_id=123`.</summary>
            [QueryParameter("team_id")]
            public double? TeamId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithField_ItemRequestBuilderPostRequestConfiguration : RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_ItemRequestBuilderPostQueryParameters>
        {
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember1"/>, <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember10"/>, <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember11"/>, <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember12"/>, <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember13"/>, <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember14"/>, <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember15"/>, <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember2"/>, <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember3"/>, <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember4"/>, <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember5"/>, <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember6"/>, <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember7"/>, <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember8"/>, <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember9"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithField_PostRequestBody : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember1? WithFieldPostRequestBodyMember1 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember1 WithFieldPostRequestBodyMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember10"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember10? WithFieldPostRequestBodyMember10 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember10 WithFieldPostRequestBodyMember10 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember11"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember11? WithFieldPostRequestBodyMember11 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember11 WithFieldPostRequestBodyMember11 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember12"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember12? WithFieldPostRequestBodyMember12 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember12 WithFieldPostRequestBodyMember12 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember13"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember13? WithFieldPostRequestBodyMember13 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember13 WithFieldPostRequestBodyMember13 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember14"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember14? WithFieldPostRequestBodyMember14 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember14 WithFieldPostRequestBodyMember14 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember15"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember15? WithFieldPostRequestBodyMember15 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember15 WithFieldPostRequestBodyMember15 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember2? WithFieldPostRequestBodyMember2 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember2 WithFieldPostRequestBodyMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember3? WithFieldPostRequestBodyMember3 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember3 WithFieldPostRequestBodyMember3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember4? WithFieldPostRequestBodyMember4 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember4 WithFieldPostRequestBodyMember4 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember5? WithFieldPostRequestBodyMember5 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember5 WithFieldPostRequestBodyMember5 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember6? WithFieldPostRequestBodyMember6 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember6 WithFieldPostRequestBodyMember6 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember7"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember7? WithFieldPostRequestBodyMember7 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember7 WithFieldPostRequestBodyMember7 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember8"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember8? WithFieldPostRequestBodyMember8 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember8 WithFieldPostRequestBodyMember8 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember9? WithFieldPostRequestBodyMember9 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember9 WithFieldPostRequestBodyMember9 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_PostRequestBody"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_PostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var result = new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_ItemRequestBuilder.WithField_PostRequestBody();
                result.WithFieldPostRequestBodyMember1 = new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember1();
                result.WithFieldPostRequestBodyMember10 = new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember10();
                result.WithFieldPostRequestBodyMember11 = new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember11();
                result.WithFieldPostRequestBodyMember12 = new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember12();
                result.WithFieldPostRequestBodyMember13 = new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember13();
                result.WithFieldPostRequestBodyMember14 = new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember14();
                result.WithFieldPostRequestBodyMember15 = new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember15();
                result.WithFieldPostRequestBodyMember2 = new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember2();
                result.WithFieldPostRequestBodyMember3 = new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember3();
                result.WithFieldPostRequestBodyMember4 = new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember4();
                result.WithFieldPostRequestBodyMember5 = new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember5();
                result.WithFieldPostRequestBodyMember6 = new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember6();
                result.WithFieldPostRequestBodyMember7 = new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember7();
                result.WithFieldPostRequestBodyMember8 = new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember8();
                result.WithFieldPostRequestBodyMember9 = new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember9();
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WithFieldPostRequestBodyMember1 != null || WithFieldPostRequestBodyMember10 != null || WithFieldPostRequestBodyMember11 != null || WithFieldPostRequestBodyMember12 != null || WithFieldPostRequestBodyMember13 != null || WithFieldPostRequestBodyMember14 != null || WithFieldPostRequestBodyMember15 != null || WithFieldPostRequestBodyMember2 != null || WithFieldPostRequestBodyMember3 != null || WithFieldPostRequestBodyMember4 != null || WithFieldPostRequestBodyMember5 != null || WithFieldPostRequestBodyMember6 != null || WithFieldPostRequestBodyMember7 != null || WithFieldPostRequestBodyMember8 != null || WithFieldPostRequestBodyMember9 != null)
                {
                    return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(WithFieldPostRequestBodyMember1, WithFieldPostRequestBodyMember10, WithFieldPostRequestBodyMember11, WithFieldPostRequestBodyMember12, WithFieldPostRequestBodyMember13, WithFieldPostRequestBodyMember14, WithFieldPostRequestBodyMember15, WithFieldPostRequestBodyMember2, WithFieldPostRequestBodyMember3, WithFieldPostRequestBodyMember4, WithFieldPostRequestBodyMember5, WithFieldPostRequestBodyMember6, WithFieldPostRequestBodyMember7, WithFieldPostRequestBodyMember8, WithFieldPostRequestBodyMember9);
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Field.Item.WithField_PostRequestBodyMember1>(null, WithFieldPostRequestBodyMember1, WithFieldPostRequestBodyMember10, WithFieldPostRequestBodyMember11, WithFieldPostRequestBodyMember12, WithFieldPostRequestBodyMember13, WithFieldPostRequestBodyMember14, WithFieldPostRequestBodyMember15, WithFieldPostRequestBodyMember2, WithFieldPostRequestBodyMember3, WithFieldPostRequestBodyMember4, WithFieldPostRequestBodyMember5, WithFieldPostRequestBodyMember6, WithFieldPostRequestBodyMember7, WithFieldPostRequestBodyMember8, WithFieldPostRequestBodyMember9);
            }
        }
    }
}
#pragma warning restore CS0618
