// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ClickUp.Api.V2.TaskNamespace.Item.Link.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\task\{task_id}\link\{links_to}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithLinks_toItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLinks_toItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/task/{task_id}/link/{links_to}{?custom_task_ids*,team_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithLinks_toItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/task/{task_id}/link/{links_to}{?custom_task_ids*,team_id*}", rawUrl)
        {
        }
        /// <summary>
        /// Remove the link between two tasks.
        /// </summary>
        /// <returns>A <see cref="global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toDeleteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toDeleteResponse?> DeleteAsWithLinks_toDeleteResponseAsync(Action<RequestConfiguration<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder.WithLinks_toItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toDeleteResponse> DeleteAsWithLinks_toDeleteResponseAsync(Action<RequestConfiguration<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder.WithLinks_toItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toDeleteResponse>(requestInfo, global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toDeleteResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Remove the link between two tasks.
        /// </summary>
        /// <returns>A <see cref="global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use DeleteAsWithLinks_toDeleteResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toResponse?> DeleteAsync(Action<RequestConfiguration<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder.WithLinks_toItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toResponse> DeleteAsync(Action<RequestConfiguration<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder.WithLinks_toItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toResponse>(requestInfo, global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This is the equivalent of the feature _Task Links_ in the right-hand sidebar of a Task.  It allows you to link two tasks together. General links or links to other objects than tasks are not supported.
        /// </summary>
        /// <returns>A <see cref="global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toPostResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toPostResponse?> PostAsWithLinks_toPostResponseAsync(Action<RequestConfiguration<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder.WithLinks_toItemRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toPostResponse> PostAsWithLinks_toPostResponseAsync(Action<RequestConfiguration<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder.WithLinks_toItemRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toPostResponse>(requestInfo, global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toPostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This is the equivalent of the feature _Task Links_ in the right-hand sidebar of a Task.  It allows you to link two tasks together. General links or links to other objects than tasks are not supported.
        /// </summary>
        /// <returns>A <see cref="global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsWithLinks_toPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toResponse?> PostAsync(Action<RequestConfiguration<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder.WithLinks_toItemRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toResponse> PostAsync(Action<RequestConfiguration<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder.WithLinks_toItemRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPostRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toResponse>(requestInfo, global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Remove the link between two tasks.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder.WithLinks_toItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder.WithLinks_toItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// This is the equivalent of the feature _Task Links_ in the right-hand sidebar of a Task.  It allows you to link two tasks together. General links or links to other objects than tasks are not supported.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder.WithLinks_toItemRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(Action<RequestConfiguration<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder.WithLinks_toItemRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Remove the link between two tasks.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithLinks_toItemRequestBuilderDeleteQueryParameters 
        {
            /// <summary>If you want to reference a task by it&apos;s custom task id, this value must be `true`.</summary>
            [QueryParameter("custom_task_ids")]
            public bool? CustomTaskIds { get; set; }
            /// <summary>When the `custom_task_ids` parameter is set to `true`, the Workspace ID must be provided using the `team_id` parameter. \For example: `custom_task_ids=true&amp;team_id=123`.</summary>
            [QueryParameter("team_id")]
            public double? TeamId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithLinks_toItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder.WithLinks_toItemRequestBuilderDeleteQueryParameters>
        {
        }
        /// <summary>
        /// This is the equivalent of the feature _Task Links_ in the right-hand sidebar of a Task.  It allows you to link two tasks together. General links or links to other objects than tasks are not supported.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithLinks_toItemRequestBuilderPostQueryParameters 
        {
            /// <summary>If you want to reference a task by it&apos;s custom task id, this value must be `true`.</summary>
            [QueryParameter("custom_task_ids")]
            public bool? CustomTaskIds { get; set; }
            /// <summary>When the `custom_task_ids` parameter is set to `true`, the Workspace ID must be provided using the `team_id` parameter. \For example: `custom_task_ids=true&amp;team_id=123`.</summary>
            [QueryParameter("team_id")]
            public double? TeamId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithLinks_toItemRequestBuilderPostRequestConfiguration : RequestConfiguration<global::ClickUp.Api.V2.TaskNamespace.Item.Link.Item.WithLinks_toItemRequestBuilder.WithLinks_toItemRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
