// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ClickUp.Api.V2.List.Item.Guest.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithGuest_PostResponse_guest_shared_lists : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The archived property</summary>
        public bool? Archived { get; set; }
        /// <summary>The assignee property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Assignee { get; set; }
#nullable restore
#else
        public string Assignee { get; set; }
#endif
        /// <summary>The due_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DueDate { get; set; }
#nullable restore
#else
        public string DueDate { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The orderindex property</summary>
        public int? Orderindex { get; set; }
        /// <summary>The override_statuses property</summary>
        public bool? OverrideStatuses { get; set; }
        /// <summary>The permission_level property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PermissionLevel { get; set; }
#nullable restore
#else
        public string PermissionLevel { get; set; }
#endif
        /// <summary>The priority property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Priority { get; set; }
#nullable restore
#else
        public string Priority { get; set; }
#endif
        /// <summary>The start_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartDate { get; set; }
#nullable restore
#else
        public string StartDate { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The statuses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<UntypedNode>? Statuses { get; set; }
#nullable restore
#else
        public List<UntypedNode> Statuses { get; set; }
#endif
        /// <summary>The task_count property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaskCount { get; set; }
#nullable restore
#else
        public string TaskCount { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ClickUp.Api.V2.List.Item.Guest.Item.WithGuest_PostResponse_guest_shared_lists"/> and sets the default values.
        /// </summary>
        public WithGuest_PostResponse_guest_shared_lists()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ClickUp.Api.V2.List.Item.Guest.Item.WithGuest_PostResponse_guest_shared_lists"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ClickUp.Api.V2.List.Item.Guest.Item.WithGuest_PostResponse_guest_shared_lists CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ClickUp.Api.V2.List.Item.Guest.Item.WithGuest_PostResponse_guest_shared_lists();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "assignee", n => { Assignee = n.GetStringValue(); } },
                { "due_date", n => { DueDate = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "orderindex", n => { Orderindex = n.GetIntValue(); } },
                { "override_statuses", n => { OverrideStatuses = n.GetBoolValue(); } },
                { "permission_level", n => { PermissionLevel = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetStringValue(); } },
                { "start_date", n => { StartDate = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "statuses", n => { Statuses = n.GetCollectionOfPrimitiveValues<UntypedNode>()?.AsList(); } },
                { "task_count", n => { TaskCount = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("archived", Archived);
            writer.WriteStringValue("assignee", Assignee);
            writer.WriteStringValue("due_date", DueDate);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("orderindex", Orderindex);
            writer.WriteBoolValue("override_statuses", OverrideStatuses);
            writer.WriteStringValue("permission_level", PermissionLevel);
            writer.WriteStringValue("priority", Priority);
            writer.WriteStringValue("start_date", StartDate);
            writer.WriteStringValue("status", Status);
            writer.WriteCollectionOfPrimitiveValues<UntypedNode>("statuses", Statuses);
            writer.WriteStringValue("task_count", TaskCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
