// <auto-generated/>
#pragma warning disable CS0618
using SyncUp.ClickUp.Api.V2.Webhook.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SyncUp.ClickUp.Api.V2.Webhook
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\webhook
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebhookRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the SyncUp.ClickUp.Api.v2.webhook.item collection</summary>
        /// <param name="position">e506-4a29-9d42-26e504e3435e (uuid)</param>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.Webhook.Item.WithWebhook_ItemRequestBuilder"/></returns>
        public global::SyncUp.ClickUp.Api.V2.Webhook.Item.WithWebhook_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("webhook_id", position);
                return new global::SyncUp.ClickUp.Api.V2.Webhook.Item.WithWebhook_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.Webhook.WebhookRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebhookRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/webhook", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.Webhook.WebhookRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WebhookRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/webhook", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
