// <auto-generated/>
#pragma warning disable CS0618
using ClickUp.Api.V2.Space.Item.Field;
using ClickUp.Api.V2.Space.Item.Folder;
using ClickUp.Api.V2.Space.Item.Folder_template;
using ClickUp.Api.V2.Space.Item.List;
using ClickUp.Api.V2.Space.Item.List_template;
using ClickUp.Api.V2.Space.Item.Tag;
using ClickUp.Api.V2.Space.Item.View;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace ClickUp.Api.V2.Space.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\space\{space_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSpace_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The field property</summary>
        public global::ClickUp.Api.V2.Space.Item.Field.FieldRequestBuilder Field
        {
            get => new global::ClickUp.Api.V2.Space.Item.Field.FieldRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The folder property</summary>
        public global::ClickUp.Api.V2.Space.Item.Folder.FolderRequestBuilder Folder
        {
            get => new global::ClickUp.Api.V2.Space.Item.Folder.FolderRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The folder_template property</summary>
        public global::ClickUp.Api.V2.Space.Item.Folder_template.Folder_templateRequestBuilder Folder_template
        {
            get => new global::ClickUp.Api.V2.Space.Item.Folder_template.Folder_templateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list property</summary>
        public global::ClickUp.Api.V2.Space.Item.List.ListRequestBuilder List
        {
            get => new global::ClickUp.Api.V2.Space.Item.List.ListRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The list_template property</summary>
        public global::ClickUp.Api.V2.Space.Item.List_template.List_templateRequestBuilder List_template
        {
            get => new global::ClickUp.Api.V2.Space.Item.List_template.List_templateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tag property</summary>
        public global::ClickUp.Api.V2.Space.Item.Tag.TagRequestBuilder Tag
        {
            get => new global::ClickUp.Api.V2.Space.Item.Tag.TagRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The view property</summary>
        public global::ClickUp.Api.V2.Space.Item.View.ViewRequestBuilder View
        {
            get => new global::ClickUp.Api.V2.Space.Item.View.ViewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ClickUp.Api.V2.Space.Item.WithSpace_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSpace_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/space/{space_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ClickUp.Api.V2.Space.Item.WithSpace_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSpace_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/space/{space_id}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a Space from your Workspace.
        /// </summary>
        /// <returns>A <see cref="global::ClickUp.Api.V2.Space.Item.WithSpace_DeleteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ClickUp.Api.V2.Space.Item.WithSpace_DeleteResponse?> DeleteAsWithSpace_DeleteResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ClickUp.Api.V2.Space.Item.WithSpace_DeleteResponse> DeleteAsWithSpace_DeleteResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::ClickUp.Api.V2.Space.Item.WithSpace_DeleteResponse>(requestInfo, global::ClickUp.Api.V2.Space.Item.WithSpace_DeleteResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a Space from your Workspace.
        /// </summary>
        /// <returns>A <see cref="global::ClickUp.Api.V2.Space.Item.WithSpace_Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use DeleteAsWithSpace_DeleteResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ClickUp.Api.V2.Space.Item.WithSpace_Response?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ClickUp.Api.V2.Space.Item.WithSpace_Response> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::ClickUp.Api.V2.Space.Item.WithSpace_Response>(requestInfo, global::ClickUp.Api.V2.Space.Item.WithSpace_Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// View the Spaces available in a Workspace.
        /// </summary>
        /// <returns>A <see cref="global::ClickUp.Api.V2.Space.Item.WithSpace_GetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ClickUp.Api.V2.Space.Item.WithSpace_GetResponse?> GetAsWithSpace_GetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ClickUp.Api.V2.Space.Item.WithSpace_GetResponse> GetAsWithSpace_GetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::ClickUp.Api.V2.Space.Item.WithSpace_GetResponse>(requestInfo, global::ClickUp.Api.V2.Space.Item.WithSpace_GetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// View the Spaces available in a Workspace.
        /// </summary>
        /// <returns>A <see cref="global::ClickUp.Api.V2.Space.Item.WithSpace_Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsWithSpace_GetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ClickUp.Api.V2.Space.Item.WithSpace_Response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ClickUp.Api.V2.Space.Item.WithSpace_Response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::ClickUp.Api.V2.Space.Item.WithSpace_Response>(requestInfo, global::ClickUp.Api.V2.Space.Item.WithSpace_Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Rename, set the Space color, and enable ClickApps for a Space.
        /// </summary>
        /// <returns>A <see cref="global::ClickUp.Api.V2.Space.Item.WithSpace_PutResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ClickUp.Api.V2.Space.Item.WithSpace_PutResponse?> PutAsWithSpace_PutResponseAsync(global::ClickUp.Api.V2.Space.Item.WithSpace_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ClickUp.Api.V2.Space.Item.WithSpace_PutResponse> PutAsWithSpace_PutResponseAsync(global::ClickUp.Api.V2.Space.Item.WithSpace_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::ClickUp.Api.V2.Space.Item.WithSpace_PutResponse>(requestInfo, global::ClickUp.Api.V2.Space.Item.WithSpace_PutResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Rename, set the Space color, and enable ClickApps for a Space.
        /// </summary>
        /// <returns>A <see cref="global::ClickUp.Api.V2.Space.Item.WithSpace_Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PutAsWithSpace_PutResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::ClickUp.Api.V2.Space.Item.WithSpace_Response?> PutAsync(global::ClickUp.Api.V2.Space.Item.WithSpace_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::ClickUp.Api.V2.Space.Item.WithSpace_Response> PutAsync(global::ClickUp.Api.V2.Space.Item.WithSpace_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::ClickUp.Api.V2.Space.Item.WithSpace_Response>(requestInfo, global::ClickUp.Api.V2.Space.Item.WithSpace_Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a Space from your Workspace.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// View the Spaces available in a Workspace.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Rename, set the Space color, and enable ClickApps for a Space.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::ClickUp.Api.V2.Space.Item.WithSpace_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::ClickUp.Api.V2.Space.Item.WithSpace_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::ClickUp.Api.V2.Space.Item.WithSpace_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::ClickUp.Api.V2.Space.Item.WithSpace_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::ClickUp.Api.V2.Space.Item.WithSpace_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithSpace_ItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithSpace_ItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithSpace_ItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
