// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SyncUp.ClickUp.Api.V2.Team.Item.Guest.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithGuest_PutResponse_guest_user : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>The custom_role property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CustomRole { get; set; }
#nullable restore
#else
        public UntypedNode CustomRole { get; set; }
#endif
        /// <summary>The date_invited property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateInvited { get; set; }
#nullable restore
#else
        public string DateInvited { get; set; }
#endif
        /// <summary>The date_joined property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateJoined { get; set; }
#nullable restore
#else
        public string DateJoined { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The initials property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Initials { get; set; }
#nullable restore
#else
        public string Initials { get; set; }
#endif
        /// <summary>The last_active property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastActive { get; set; }
#nullable restore
#else
        public string LastActive { get; set; }
#endif
        /// <summary>The profilePicture property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfilePicture { get; set; }
#nullable restore
#else
        public string ProfilePicture { get; set; }
#endif
        /// <summary>The role property</summary>
        public int? Role { get; set; }
        /// <summary>The username property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.Team.Item.Guest.Item.WithGuest_PutResponse_guest_user"/> and sets the default values.
        /// </summary>
        public WithGuest_PutResponse_guest_user()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.Team.Item.Guest.Item.WithGuest_PutResponse_guest_user"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SyncUp.ClickUp.Api.V2.Team.Item.Guest.Item.WithGuest_PutResponse_guest_user CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SyncUp.ClickUp.Api.V2.Team.Item.Guest.Item.WithGuest_PutResponse_guest_user();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "color", n => { Color = n.GetStringValue(); } },
                { "custom_role", n => { CustomRole = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "date_invited", n => { DateInvited = n.GetStringValue(); } },
                { "date_joined", n => { DateJoined = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "initials", n => { Initials = n.GetStringValue(); } },
                { "last_active", n => { LastActive = n.GetStringValue(); } },
                { "profilePicture", n => { ProfilePicture = n.GetStringValue(); } },
                { "role", n => { Role = n.GetIntValue(); } },
                { "username", n => { Username = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("color", Color);
            writer.WriteObjectValue<UntypedNode>("custom_role", CustomRole);
            writer.WriteStringValue("date_invited", DateInvited);
            writer.WriteStringValue("date_joined", DateJoined);
            writer.WriteStringValue("email", Email);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("initials", Initials);
            writer.WriteStringValue("last_active", LastActive);
            writer.WriteStringValue("profilePicture", ProfilePicture);
            writer.WriteIntValue("role", Role);
            writer.WriteStringValue("username", Username);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
