// <auto-generated/>
#pragma warning disable CS0618
using SyncUp.ClickUp.Api.V2.View.Item.Comment;
using SyncUp.ClickUp.Api.V2.View.Item.TaskNamespace;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SyncUp.ClickUp.Api.V2.View.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\view\{view_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithView_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The comment property</summary>
        public global::SyncUp.ClickUp.Api.V2.View.Item.Comment.CommentRequestBuilder Comment
        {
            get => new global::SyncUp.ClickUp.Api.V2.View.Item.Comment.CommentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The task property</summary>
        public global::SyncUp.ClickUp.Api.V2.View.Item.TaskNamespace.TaskRequestBuilder Task
        {
            get => new global::SyncUp.ClickUp.Api.V2.View.Item.TaskNamespace.TaskRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithView_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/view/{view_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithView_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/view/{view_id}", rawUrl)
        {
        }
        /// <summary>
        /// Delete View
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_DeleteResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_DeleteResponse?> DeleteAsWithView_DeleteResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_DeleteResponse> DeleteAsWithView_DeleteResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_DeleteResponse>(requestInfo, global::SyncUp.ClickUp.Api.V2.View.Item.WithView_DeleteResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete View
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use DeleteAsWithView_DeleteResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_Response?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_Response> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_Response>(requestInfo, global::SyncUp.ClickUp.Api.V2.View.Item.WithView_Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// View information about a specific task or page view. The information returned about a view varies by the type of view.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder.WithView_GetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder.WithView_GetResponse?> GetAsWithView_GetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder.WithView_GetResponse> GetAsWithView_GetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder.WithView_GetResponse>(requestInfo, global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder.WithView_GetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// View information about a specific task or page view. The information returned about a view varies by the type of view.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder.WithView_Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsWithView_GetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder.WithView_Response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder.WithView_Response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder.WithView_Response>(requestInfo, global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder.WithView_Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Rename a view, update the grouping, sorting, filters, columns, and settings of a view.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_PutResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_PutResponse?> PutAsWithView_PutResponseAsync(global::SyncUp.ClickUp.Api.V2.View.Item.WithView_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_PutResponse> PutAsWithView_PutResponseAsync(global::SyncUp.ClickUp.Api.V2.View.Item.WithView_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_PutResponse>(requestInfo, global::SyncUp.ClickUp.Api.V2.View.Item.WithView_PutResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Rename a view, update the grouping, sorting, filters, columns, and settings of a view.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_Response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PutAsWithView_PutResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_Response?> PutAsync(global::SyncUp.ClickUp.Api.V2.View.Item.WithView_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_Response> PutAsync(global::SyncUp.ClickUp.Api.V2.View.Item.WithView_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_Response>(requestInfo, global::SyncUp.ClickUp.Api.V2.View.Item.WithView_Response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete View
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// View information about a specific task or page view. The information returned about a view varies by the type of view.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Rename a view, update the grouping, sorting, filters, columns, and settings of a view.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::SyncUp.ClickUp.Api.V2.View.Item.WithView_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::SyncUp.ClickUp.Api.V2.View.Item.WithView_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember1"/>, <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithView_GetResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember1? WithViewGetResponseMember1 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember1 WithViewGetResponseMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2? WithViewGetResponseMember2 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2 WithViewGetResponseMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder.WithView_GetResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder.WithView_GetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder.WithView_GetResponse();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithViewGetResponseMember1 = new global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithViewGetResponseMember2 = new global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WithViewGetResponseMember1 != null)
                {
                    return WithViewGetResponseMember1.GetFieldDeserializers();
                }
                else if(WithViewGetResponseMember2 != null)
                {
                    return WithViewGetResponseMember2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(WithViewGetResponseMember1 != null)
                {
                    writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember1>(null, WithViewGetResponseMember1);
                }
                else if(WithViewGetResponseMember2 != null)
                {
                    writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2>(null, WithViewGetResponseMember2);
                }
            }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithView_ItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithView_ItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithView_ItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember1"/>, <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithView_Response : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember1? WithViewGetResponseMember1 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember1 WithViewGetResponseMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2? WithViewGetResponseMember2 { get; set; }
#nullable restore
#else
            public global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2 WithViewGetResponseMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder.WithView_Response"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder.WithView_Response CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::SyncUp.ClickUp.Api.V2.View.Item.WithView_ItemRequestBuilder.WithView_Response();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithViewGetResponseMember1 = new global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithViewGetResponseMember2 = new global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WithViewGetResponseMember1 != null)
                {
                    return WithViewGetResponseMember1.GetFieldDeserializers();
                }
                else if(WithViewGetResponseMember2 != null)
                {
                    return WithViewGetResponseMember2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(WithViewGetResponseMember1 != null)
                {
                    writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember1>(null, WithViewGetResponseMember1);
                }
                else if(WithViewGetResponseMember2 != null)
                {
                    writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2>(null, WithViewGetResponseMember2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
