// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SyncUp.ClickUp.Api.V2.View.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithView_GetResponseMember2_view : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The creator property</summary>
        public int? Creator { get; set; }
        /// <summary>The date_created property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateCreated { get; set; }
#nullable restore
#else
        public string DateCreated { get; set; }
#endif
        /// <summary>The date_protected property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? DateProtected { get; set; }
#nullable restore
#else
        public UntypedNode DateProtected { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The orderindex property</summary>
        public int? Orderindex { get; set; }
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2_view_parent? Parent { get; set; }
#nullable restore
#else
        public global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2_view_parent Parent { get; set; }
#endif
        /// <summary>The protected property</summary>
        public bool? Protected { get; set; }
        /// <summary>The protected_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? ProtectedBy { get; set; }
#nullable restore
#else
        public UntypedNode ProtectedBy { get; set; }
#endif
        /// <summary>The protected_note property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? ProtectedNote { get; set; }
#nullable restore
#else
        public UntypedNode ProtectedNote { get; set; }
#endif
        /// <summary>The public property</summary>
        public bool? Public { get; set; }
        /// <summary>The public_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublicUrl { get; set; }
#nullable restore
#else
        public string PublicUrl { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2_view_type? Type { get; set; }
        /// <summary>The visibility property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Visibility { get; set; }
#nullable restore
#else
        public string Visibility { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2_view"/> and sets the default values.
        /// </summary>
        public WithView_GetResponseMember2_view()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2_view"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2_view CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2_view();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "creator", n => { Creator = n.GetIntValue(); } },
                { "date_created", n => { DateCreated = n.GetStringValue(); } },
                { "date_protected", n => { DateProtected = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "orderindex", n => { Orderindex = n.GetIntValue(); } },
                { "parent", n => { Parent = n.GetObjectValue<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2_view_parent>(global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2_view_parent.CreateFromDiscriminatorValue); } },
                { "protected", n => { Protected = n.GetBoolValue(); } },
                { "protected_by", n => { ProtectedBy = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "protected_note", n => { ProtectedNote = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "public", n => { Public = n.GetBoolValue(); } },
                { "public_url", n => { PublicUrl = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2_view_type>(); } },
                { "visibility", n => { Visibility = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("creator", Creator);
            writer.WriteStringValue("date_created", DateCreated);
            writer.WriteObjectValue<UntypedNode>("date_protected", DateProtected);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("orderindex", Orderindex);
            writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2_view_parent>("parent", Parent);
            writer.WriteBoolValue("protected", Protected);
            writer.WriteObjectValue<UntypedNode>("protected_by", ProtectedBy);
            writer.WriteObjectValue<UntypedNode>("protected_note", ProtectedNote);
            writer.WriteBoolValue("public", Public);
            writer.WriteStringValue("public_url", PublicUrl);
            writer.WriteEnumValue<global::SyncUp.ClickUp.Api.V2.View.Item.WithView_GetResponseMember2_view_type>("type", Type);
            writer.WriteStringValue("visibility", Visibility);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
