// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SyncUp.ClickUp.Api.V2.Team.Item.Time_entries
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Time_entriesGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The approval property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Approval { get; set; }
#nullable restore
#else
        public UntypedNode Approval { get; set; }
#endif
        /// <summary>ID of the associated approval</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ApprovalId { get; set; }
#nullable restore
#else
        public string ApprovalId { get; set; }
#endif
        /// <summary>The at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? At { get; set; }
#nullable restore
#else
        public string At { get; set; }
#endif
        /// <summary>The billable property</summary>
        public bool? Billable { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The duration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Duration { get; set; }
#nullable restore
#else
        public string Duration { get; set; }
#endif
        /// <summary>The end property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? End { get; set; }
#nullable restore
#else
        public string End { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>The start property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Start { get; set; }
#nullable restore
#else
        public string Start { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The task property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Time_entries.Time_entriesGetResponse_data_task? Task { get; set; }
#nullable restore
#else
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Time_entries.Time_entriesGetResponse_data_task Task { get; set; }
#endif
        /// <summary>The task_location property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? TaskLocation { get; set; }
#nullable restore
#else
        public UntypedNode TaskLocation { get; set; }
#endif
        /// <summary>The task_tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<UntypedNode>? TaskTags { get; set; }
#nullable restore
#else
        public List<UntypedNode> TaskTags { get; set; }
#endif
        /// <summary>The task_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TaskUrl { get; set; }
#nullable restore
#else
        public string TaskUrl { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? User { get; set; }
#nullable restore
#else
        public UntypedNode User { get; set; }
#endif
        /// <summary>The wid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Wid { get; set; }
#nullable restore
#else
        public string Wid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.Team.Item.Time_entries.Time_entriesGetResponse_data"/> and sets the default values.
        /// </summary>
        public Time_entriesGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.Team.Item.Time_entries.Time_entriesGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SyncUp.ClickUp.Api.V2.Team.Item.Time_entries.Time_entriesGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SyncUp.ClickUp.Api.V2.Team.Item.Time_entries.Time_entriesGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "approval", n => { Approval = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "approval_id", n => { ApprovalId = n.GetStringValue(); } },
                { "at", n => { At = n.GetStringValue(); } },
                { "billable", n => { Billable = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "duration", n => { Duration = n.GetStringValue(); } },
                { "end", n => { End = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "source", n => { Source = n.GetStringValue(); } },
                { "start", n => { Start = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "task", n => { Task = n.GetObjectValue<global::SyncUp.ClickUp.Api.V2.Team.Item.Time_entries.Time_entriesGetResponse_data_task>(global::SyncUp.ClickUp.Api.V2.Team.Item.Time_entries.Time_entriesGetResponse_data_task.CreateFromDiscriminatorValue); } },
                { "task_location", n => { TaskLocation = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "task_tags", n => { TaskTags = n.GetCollectionOfPrimitiveValues<UntypedNode>()?.AsList(); } },
                { "task_url", n => { TaskUrl = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "wid", n => { Wid = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("approval", Approval);
            writer.WriteStringValue("approval_id", ApprovalId);
            writer.WriteStringValue("at", At);
            writer.WriteBoolValue("billable", Billable);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("duration", Duration);
            writer.WriteStringValue("end", End);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("source", Source);
            writer.WriteStringValue("start", Start);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.Team.Item.Time_entries.Time_entriesGetResponse_data_task>("task", Task);
            writer.WriteObjectValue<UntypedNode>("task_location", TaskLocation);
            writer.WriteCollectionOfPrimitiveValues<UntypedNode>("task_tags", TaskTags);
            writer.WriteStringValue("task_url", TaskUrl);
            writer.WriteObjectValue<UntypedNode>("user", User);
            writer.WriteStringValue("wid", Wid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
