// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SyncUp.ClickUp.Api.V2.Team.Item.Space
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SpacePostResponse_features : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The checklists property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Checklists { get; set; }
#nullable restore
#else
        public UntypedNode Checklists { get; set; }
#endif
        /// <summary>The custom_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? CustomFields { get; set; }
#nullable restore
#else
        public UntypedNode CustomFields { get; set; }
#endif
        /// <summary>The custom_items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_custom_items? CustomItems { get; set; }
#nullable restore
#else
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_custom_items CustomItems { get; set; }
#endif
        /// <summary>The dependency_warning property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? DependencyWarning { get; set; }
#nullable restore
#else
        public UntypedNode DependencyWarning { get; set; }
#endif
        /// <summary>The due_dates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? DueDates { get; set; }
#nullable restore
#else
        public UntypedNode DueDates { get; set; }
#endif
        /// <summary>The emails property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_emails? Emails { get; set; }
#nullable restore
#else
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_emails Emails { get; set; }
#endif
        /// <summary>The milestones property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_milestones? Milestones { get; set; }
#nullable restore
#else
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_milestones Milestones { get; set; }
#endif
        /// <summary>The multiple_assignees property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_multiple_assignees? MultipleAssignees { get; set; }
#nullable restore
#else
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_multiple_assignees MultipleAssignees { get; set; }
#endif
        /// <summary>The points property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_points? Points { get; set; }
#nullable restore
#else
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_points Points { get; set; }
#endif
        /// <summary>The portfolios property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Portfolios { get; set; }
#nullable restore
#else
        public UntypedNode Portfolios { get; set; }
#endif
        /// <summary>The remap_dependencies property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? RemapDependencies { get; set; }
#nullable restore
#else
        public UntypedNode RemapDependencies { get; set; }
#endif
        /// <summary>The sprints property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_sprints? Sprints { get; set; }
#nullable restore
#else
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_sprints Sprints { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Tags { get; set; }
#nullable restore
#else
        public UntypedNode Tags { get; set; }
#endif
        /// <summary>The time_estimates property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? TimeEstimates { get; set; }
#nullable restore
#else
        public UntypedNode TimeEstimates { get; set; }
#endif
        /// <summary>The zoom property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_zoom? Zoom { get; set; }
#nullable restore
#else
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_zoom Zoom { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features"/> and sets the default values.
        /// </summary>
        public SpacePostResponse_features()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "checklists", n => { Checklists = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "custom_fields", n => { CustomFields = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "custom_items", n => { CustomItems = n.GetObjectValue<global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_custom_items>(global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_custom_items.CreateFromDiscriminatorValue); } },
                { "dependency_warning", n => { DependencyWarning = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "due_dates", n => { DueDates = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "emails", n => { Emails = n.GetObjectValue<global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_emails>(global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_emails.CreateFromDiscriminatorValue); } },
                { "milestones", n => { Milestones = n.GetObjectValue<global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_milestones>(global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_milestones.CreateFromDiscriminatorValue); } },
                { "multiple_assignees", n => { MultipleAssignees = n.GetObjectValue<global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_multiple_assignees>(global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_multiple_assignees.CreateFromDiscriminatorValue); } },
                { "points", n => { Points = n.GetObjectValue<global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_points>(global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_points.CreateFromDiscriminatorValue); } },
                { "portfolios", n => { Portfolios = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "remap_dependencies", n => { RemapDependencies = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "sprints", n => { Sprints = n.GetObjectValue<global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_sprints>(global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_sprints.CreateFromDiscriminatorValue); } },
                { "tags", n => { Tags = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "time_estimates", n => { TimeEstimates = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "zoom", n => { Zoom = n.GetObjectValue<global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_zoom>(global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_zoom.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<UntypedNode>("checklists", Checklists);
            writer.WriteObjectValue<UntypedNode>("custom_fields", CustomFields);
            writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_custom_items>("custom_items", CustomItems);
            writer.WriteObjectValue<UntypedNode>("dependency_warning", DependencyWarning);
            writer.WriteObjectValue<UntypedNode>("due_dates", DueDates);
            writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_emails>("emails", Emails);
            writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_milestones>("milestones", Milestones);
            writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_multiple_assignees>("multiple_assignees", MultipleAssignees);
            writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_points>("points", Points);
            writer.WriteObjectValue<UntypedNode>("portfolios", Portfolios);
            writer.WriteObjectValue<UntypedNode>("remap_dependencies", RemapDependencies);
            writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_sprints>("sprints", Sprints);
            writer.WriteObjectValue<UntypedNode>("tags", Tags);
            writer.WriteObjectValue<UntypedNode>("time_estimates", TimeEstimates);
            writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpacePostResponse_features_zoom>("zoom", Zoom);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
