// <auto-generated/>
#pragma warning disable CS0618
using ClickUp.Api.V2.List.Item.Guest.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace ClickUp.Api.V2.List.Item.Guest
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\list\{list_id}\guest
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GuestRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the ClickUp.Api.v2.list.item.guest.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ClickUp.Api.V2.List.Item.Guest.Item.WithGuest_ItemRequestBuilder"/></returns>
        public global::ClickUp.Api.V2.List.Item.Guest.Item.WithGuest_ItemRequestBuilder this[double position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("guest_id", position);
                return new global::ClickUp.Api.V2.List.Item.Guest.Item.WithGuest_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the ClickUp.Api.v2.list.item.guest.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::ClickUp.Api.V2.List.Item.Guest.Item.WithGuest_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::ClickUp.Api.V2.List.Item.Guest.Item.WithGuest_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("guest_id", position);
                return new global::ClickUp.Api.V2.List.Item.Guest.Item.WithGuest_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ClickUp.Api.V2.List.Item.Guest.GuestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GuestRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/list/{list_id}/guest", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::ClickUp.Api.V2.List.Item.Guest.GuestRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GuestRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/list/{list_id}/guest", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
