// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ClickUp.Api.V2.Space.Item.List_template.Item
{
    /// <summary>
    /// Response object returned when a new List is created from a template in a Folder or Space.
    /// </summary>
    [Obsolete("This class is obsolete. Use WithTemplate_PostResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTemplate_Response : global::ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse, IParsable
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_Response();
        }
    }
}
#pragma warning restore CS0618
