// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item
{
    /// <summary>
    /// Detailed information about the created List
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTemplate_PostResponse_list : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Indicates if the List is archived</summary>
        public bool? Archived { get; set; }
        /// <summary>Default assignee for the List, if applicable</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Assignee { get; set; }
#nullable restore
#else
        public string Assignee { get; set; }
#endif
        /// <summary>Indicates if the List has been marked as deleted</summary>
        public bool? Deleted { get; set; }
        /// <summary>Default due date for tasks in the List</summary>
        public DateTimeOffset? DueDate { get; set; }
        /// <summary>Information about the parent Folder containing this List, if applicable</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list_folder? Folder { get; set; }
#nullable restore
#else
        public global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list_folder Folder { get; set; }
#endif
        /// <summary>Unique identifier of the List (matches parent id)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Email address that can be used to create tasks in this List via email</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InboundAddress { get; set; }
#nullable restore
#else
        public string InboundAddress { get; set; }
#endif
        /// <summary>Display name of the List</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Position of the List relative to other Lists in the same container</summary>
        public int? Orderindex { get; set; }
        /// <summary>Indicates if this List uses custom statuses instead of Space default statuses</summary>
        public bool? OverrideStatuses { get; set; }
        /// <summary>Access level the current user has for this List (e.g., create, edit, view)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PermissionLevel { get; set; }
#nullable restore
#else
        public string PermissionLevel { get; set; }
#endif
        /// <summary>Priority level of the List, if applicable</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Priority { get; set; }
#nullable restore
#else
        public string Priority { get; set; }
#endif
        /// <summary>Information about the Workspace Space containing this List</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list_space? Space { get; set; }
#nullable restore
#else
        public global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list_space Space { get; set; }
#endif
        /// <summary>Default start date for tasks in the List</summary>
        public DateTimeOffset? StartDate { get; set; }
        /// <summary>List of available statuses for tasks in this List</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list_statuses>? Statuses { get; set; }
#nullable restore
#else
        public List<global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list_statuses> Statuses { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list"/> and sets the default values.
        /// </summary>
        public WithTemplate_PostResponse_list()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "assignee", n => { Assignee = n.GetStringValue(); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "due_date", n => { DueDate = n.GetDateTimeOffsetValue(); } },
                { "folder", n => { Folder = n.GetObjectValue<global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list_folder>(global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list_folder.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "inbound_address", n => { InboundAddress = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "orderindex", n => { Orderindex = n.GetIntValue(); } },
                { "override_statuses", n => { OverrideStatuses = n.GetBoolValue(); } },
                { "permission_level", n => { PermissionLevel = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetStringValue(); } },
                { "space", n => { Space = n.GetObjectValue<global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list_space>(global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list_space.CreateFromDiscriminatorValue); } },
                { "start_date", n => { StartDate = n.GetDateTimeOffsetValue(); } },
                { "statuses", n => { Statuses = n.GetCollectionOfObjectValues<global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list_statuses>(global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list_statuses.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("archived", Archived);
            writer.WriteStringValue("assignee", Assignee);
            writer.WriteBoolValue("deleted", Deleted);
            writer.WriteDateTimeOffsetValue("due_date", DueDate);
            writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list_folder>("folder", Folder);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("inbound_address", InboundAddress);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("orderindex", Orderindex);
            writer.WriteBoolValue("override_statuses", OverrideStatuses);
            writer.WriteStringValue("permission_level", PermissionLevel);
            writer.WriteStringValue("priority", Priority);
            writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list_space>("space", Space);
            writer.WriteDateTimeOffsetValue("start_date", StartDate);
            writer.WriteCollectionOfObjectValues<global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostResponse_list_statuses>("statuses", Statuses);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
