// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item
{
    /// <summary>
    /// Options for creating the List
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTemplate_PostRequestBody_options : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Include archived tasks</summary>
        public int? Archived { get; set; }
        /// <summary>Import tasks&apos; attachments</summary>
        public bool? Attachments { get; set; }
        /// <summary>Import automation settings</summary>
        public bool? Automation { get; set; }
        /// <summary>Import tasks&apos; comments</summary>
        public bool? Comment { get; set; }
        /// <summary>Import tasks&apos; comment attachments</summary>
        public bool? CommentAttachments { get; set; }
        /// <summary>List description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Content { get; set; }
#nullable restore
#else
        public string Content { get; set; }
#endif
        /// <summary>Import tasks&apos; Custom Fields</summary>
        public bool? CustomFields { get; set; }
        /// <summary>Import tasks&apos; task types</summary>
        public bool? CustomType { get; set; }
        /// <summary>Project due date for remapping dates</summary>
        public DateTimeOffset? DueDate { get; set; }
        /// <summary>Import tasks&apos; external dependencies</summary>
        public bool? ExternalDependencies { get; set; }
        /// <summary>Import views</summary>
        public bool? IncludeViews { get; set; }
        /// <summary>Import tasks&apos; internal dependencies</summary>
        public bool? InternalDependencies { get; set; }
        /// <summary>Import tasks&apos; assignees</summary>
        public bool? OldAssignees { get; set; }
        /// <summary>Import tasks&apos; checklists</summary>
        public bool? OldChecklists { get; set; }
        /// <summary>Import tasks&apos; due dates</summary>
        public bool? OldDueDate { get; set; }
        /// <summary>Import tasks&apos; watchers</summary>
        public bool? OldFollowers { get; set; }
        /// <summary>Import tasks&apos; start dates</summary>
        public bool? OldStartDate { get; set; }
        /// <summary>Import tasks&apos; current statuses</summary>
        public bool? OldStatus { get; set; }
        /// <summary>Import tasks&apos; status settings</summary>
        public bool? OldStatuses { get; set; }
        /// <summary>Import tasks&apos; subtask assignees</summary>
        public bool? OldSubtaskAssignees { get; set; }
        /// <summary>Import tasks&apos; tags</summary>
        public bool? OldTags { get; set; }
        /// <summary>Import tasks&apos; priorities</summary>
        public bool? Priority { get; set; }
        /// <summary>Import tasks&apos; recurring settings</summary>
        public bool? RecurSettings { get; set; }
        /// <summary>Import tasks&apos; relationships</summary>
        public bool? Relationships { get; set; }
        /// <summary>Remap start dates</summary>
        public bool? RemapStartDate { get; set; }
        /// <summary>Flag if newly created Object ID should be returned without waiting for the asset itself and all its nested assets to be applied. If set to true, access checks are performed before returning, but the object might not be fully created yet. In case of a timeout on syncronous requests, the of objects from the template will continue to be created past the timeout.</summary>
        public bool? ReturnImmediately { get; set; }
        /// <summary>Skip weekends when remapping dates</summary>
        public bool? SkipWeekends { get; set; }
        /// <summary>Project start date for remapping dates</summary>
        public DateTimeOffset? StartDate { get; set; }
        /// <summary>Import tasks&apos; subtasks</summary>
        public bool? Subtasks { get; set; }
        /// <summary>Include time (hours, minutes and seconds)</summary>
        public double? TimeEstimate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostRequestBody_options"/> and sets the default values.
        /// </summary>
        public WithTemplate_PostRequestBody_options()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostRequestBody_options"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostRequestBody_options CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SyncUp.ClickUp.Api.V2.Space.Item.List_template.Item.WithTemplate_PostRequestBody_options();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archived", n => { Archived = n.GetIntValue(); } },
                { "attachments", n => { Attachments = n.GetBoolValue(); } },
                { "automation", n => { Automation = n.GetBoolValue(); } },
                { "comment", n => { Comment = n.GetBoolValue(); } },
                { "comment_attachments", n => { CommentAttachments = n.GetBoolValue(); } },
                { "content", n => { Content = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetBoolValue(); } },
                { "custom_type", n => { CustomType = n.GetBoolValue(); } },
                { "due_date", n => { DueDate = n.GetDateTimeOffsetValue(); } },
                { "external_dependencies", n => { ExternalDependencies = n.GetBoolValue(); } },
                { "include_views", n => { IncludeViews = n.GetBoolValue(); } },
                { "internal_dependencies", n => { InternalDependencies = n.GetBoolValue(); } },
                { "old_assignees", n => { OldAssignees = n.GetBoolValue(); } },
                { "old_checklists", n => { OldChecklists = n.GetBoolValue(); } },
                { "old_due_date", n => { OldDueDate = n.GetBoolValue(); } },
                { "old_followers", n => { OldFollowers = n.GetBoolValue(); } },
                { "old_start_date", n => { OldStartDate = n.GetBoolValue(); } },
                { "old_status", n => { OldStatus = n.GetBoolValue(); } },
                { "old_statuses", n => { OldStatuses = n.GetBoolValue(); } },
                { "old_subtask_assignees", n => { OldSubtaskAssignees = n.GetBoolValue(); } },
                { "old_tags", n => { OldTags = n.GetBoolValue(); } },
                { "priority", n => { Priority = n.GetBoolValue(); } },
                { "recur_settings", n => { RecurSettings = n.GetBoolValue(); } },
                { "relationships", n => { Relationships = n.GetBoolValue(); } },
                { "remap_start_date", n => { RemapStartDate = n.GetBoolValue(); } },
                { "return_immediately", n => { ReturnImmediately = n.GetBoolValue(); } },
                { "skip_weekends", n => { SkipWeekends = n.GetBoolValue(); } },
                { "start_date", n => { StartDate = n.GetDateTimeOffsetValue(); } },
                { "subtasks", n => { Subtasks = n.GetBoolValue(); } },
                { "time_estimate", n => { TimeEstimate = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("archived", Archived);
            writer.WriteBoolValue("attachments", Attachments);
            writer.WriteBoolValue("automation", Automation);
            writer.WriteBoolValue("comment", Comment);
            writer.WriteBoolValue("comment_attachments", CommentAttachments);
            writer.WriteStringValue("content", Content);
            writer.WriteBoolValue("custom_fields", CustomFields);
            writer.WriteBoolValue("custom_type", CustomType);
            writer.WriteDateTimeOffsetValue("due_date", DueDate);
            writer.WriteBoolValue("external_dependencies", ExternalDependencies);
            writer.WriteBoolValue("include_views", IncludeViews);
            writer.WriteBoolValue("internal_dependencies", InternalDependencies);
            writer.WriteBoolValue("old_assignees", OldAssignees);
            writer.WriteBoolValue("old_checklists", OldChecklists);
            writer.WriteBoolValue("old_due_date", OldDueDate);
            writer.WriteBoolValue("old_followers", OldFollowers);
            writer.WriteBoolValue("old_start_date", OldStartDate);
            writer.WriteBoolValue("old_status", OldStatus);
            writer.WriteBoolValue("old_statuses", OldStatuses);
            writer.WriteBoolValue("old_subtask_assignees", OldSubtaskAssignees);
            writer.WriteBoolValue("old_tags", OldTags);
            writer.WriteBoolValue("priority", Priority);
            writer.WriteBoolValue("recur_settings", RecurSettings);
            writer.WriteBoolValue("relationships", Relationships);
            writer.WriteBoolValue("remap_start_date", RemapStartDate);
            writer.WriteBoolValue("return_immediately", ReturnImmediately);
            writer.WriteBoolValue("skip_weekends", SkipWeekends);
            writer.WriteDateTimeOffsetValue("start_date", StartDate);
            writer.WriteBoolValue("subtasks", Subtasks);
            writer.WriteDoubleValue("time_estimate", TimeEstimate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
