// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\task\{task_id}\comment
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CommentRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CommentRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/task/{task_id}/comment{?custom_task_ids*,start*,start_id*,team_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CommentRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/task/{task_id}/comment{?custom_task_ids*,start*,start_id*,team_id*}", rawUrl)
        {
        }
        /// <summary>
        /// View task comments. \ \Retrieve comments from a task. Results are returned in reverse chronological order (newest to oldest). By default, the request returns the 25 most recent comments.\ \[Pagination](https://developer.clickup.com/docs/task-comments-pagination): To fetch the next page of history (older comments), you must use the `start` and `start_id` parameters together, using the data from the last comment of the current response.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentGetResponse?> GetAsCommentGetResponseAsync(Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder.CommentRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentGetResponse> GetAsCommentGetResponseAsync(Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder.CommentRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentGetResponse>(requestInfo, global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// View task comments. \ \Retrieve comments from a task. Results are returned in reverse chronological order (newest to oldest). By default, the request returns the 25 most recent comments.\ \[Pagination](https://developer.clickup.com/docs/task-comments-pagination): To fetch the next page of history (older comments), you must use the `start` and `start_id` parameters together, using the data from the last comment of the current response.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsCommentGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentResponse?> GetAsync(Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder.CommentRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentResponse> GetAsync(Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder.CommentRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentResponse>(requestInfo, global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Add a new comment to a task.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentPostResponse?> PostAsCommentPostResponseAsync(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentPostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder.CommentRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentPostResponse> PostAsCommentPostResponseAsync(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentPostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder.CommentRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentPostResponse>(requestInfo, global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentPostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Add a new comment to a task.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsCommentPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentResponse?> PostAsync(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentPostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder.CommentRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentResponse> PostAsync(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentPostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder.CommentRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentResponse>(requestInfo, global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// View task comments. \ \Retrieve comments from a task. Results are returned in reverse chronological order (newest to oldest). By default, the request returns the 25 most recent comments.\ \[Pagination](https://developer.clickup.com/docs/task-comments-pagination): To fetch the next page of history (older comments), you must use the `start` and `start_id` parameters together, using the data from the last comment of the current response.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder.CommentRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder.CommentRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Add a new comment to a task.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentPostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder.CommentRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentPostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder.CommentRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// View task comments. \ \Retrieve comments from a task. Results are returned in reverse chronological order (newest to oldest). By default, the request returns the 25 most recent comments.\ \[Pagination](https://developer.clickup.com/docs/task-comments-pagination): To fetch the next page of history (older comments), you must use the `start` and `start_id` parameters together, using the data from the last comment of the current response.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CommentRequestBuilderGetQueryParameters 
        {
            /// <summary>If you want to reference a task by it&apos;s custom task id, this value must be `true`.</summary>
            [QueryParameter("custom_task_ids")]
            public bool? CustomTaskIds { get; set; }
            /// <summary>The Unix timestamp (in milliseconds) of the reference comment. Required for pagination. Must be used in combination with `start_id`.\ Value should be the `date` of the last comment from the previous response.</summary>
            [QueryParameter("start")]
            public int? Start { get; set; }
            /// <summary>The unique ID of the reference comment. Required for pagination. Must be used in combination with `start`. \ Value should be the `id` of the last comment from the previous response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("start_id")]
            public string? StartId { get; set; }
#nullable restore
#else
            [QueryParameter("start_id")]
            public string StartId { get; set; }
#endif
            /// <summary>When the `custom_task_ids` parameter is set to `true`, the Workspace ID must be provided using the `team_id` parameter. \For example: `custom_task_ids=true&amp;team_id=123`.</summary>
            [QueryParameter("team_id")]
            public double? TeamId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CommentRequestBuilderGetRequestConfiguration : RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder.CommentRequestBuilderGetQueryParameters>
        {
        }
        /// <summary>
        /// Add a new comment to a task.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CommentRequestBuilderPostQueryParameters 
        {
            /// <summary>If you want to reference a task by it&apos;s custom task id, this value must be `true`.</summary>
            [QueryParameter("custom_task_ids")]
            public bool? CustomTaskIds { get; set; }
            /// <summary>When the `custom_task_ids` parameter is set to `true`, the Workspace ID must be provided using the `team_id` parameter. \For example: `custom_task_ids=true&amp;team_id=123`.</summary>
            [QueryParameter("team_id")]
            public double? TeamId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CommentRequestBuilderPostRequestConfiguration : RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Comment.CommentRequestBuilder.CommentRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
