// <auto-generated/>
#pragma warning disable CS0618
using SyncUp.ClickUp.Api.V2.Team.Item.Custom_item;
using SyncUp.ClickUp.Api.V2.Team.Item.Customroles;
using SyncUp.ClickUp.Api.V2.Team.Item.Field;
using SyncUp.ClickUp.Api.V2.Team.Item.Goal;
using SyncUp.ClickUp.Api.V2.Team.Item.Group;
using SyncUp.ClickUp.Api.V2.Team.Item.Guest;
using SyncUp.ClickUp.Api.V2.Team.Item.Plan;
using SyncUp.ClickUp.Api.V2.Team.Item.Seats;
using SyncUp.ClickUp.Api.V2.Team.Item.Shared;
using SyncUp.ClickUp.Api.V2.Team.Item.Space;
using SyncUp.ClickUp.Api.V2.Team.Item.TaskNamespace;
using SyncUp.ClickUp.Api.V2.Team.Item.TaskTemplate;
using SyncUp.ClickUp.Api.V2.Team.Item.Time_entries;
using SyncUp.ClickUp.Api.V2.Team.Item.User;
using SyncUp.ClickUp.Api.V2.Team.Item.View;
using SyncUp.ClickUp.Api.V2.Team.Item.Webhook;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SyncUp.ClickUp.Api.V2.Team.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\team\{team_-id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Team_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The custom_item property</summary>
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Custom_item.Custom_itemRequestBuilder Custom_item
        {
            get => new global::SyncUp.ClickUp.Api.V2.Team.Item.Custom_item.Custom_itemRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The customroles property</summary>
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Customroles.CustomrolesRequestBuilder Customroles
        {
            get => new global::SyncUp.ClickUp.Api.V2.Team.Item.Customroles.CustomrolesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The field property</summary>
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Field.FieldRequestBuilder Field
        {
            get => new global::SyncUp.ClickUp.Api.V2.Team.Item.Field.FieldRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The goal property</summary>
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Goal.GoalRequestBuilder Goal
        {
            get => new global::SyncUp.ClickUp.Api.V2.Team.Item.Goal.GoalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The group property</summary>
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Group.GroupRequestBuilder Group
        {
            get => new global::SyncUp.ClickUp.Api.V2.Team.Item.Group.GroupRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The guest property</summary>
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Guest.GuestRequestBuilder Guest
        {
            get => new global::SyncUp.ClickUp.Api.V2.Team.Item.Guest.GuestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The plan property</summary>
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Plan.PlanRequestBuilder Plan
        {
            get => new global::SyncUp.ClickUp.Api.V2.Team.Item.Plan.PlanRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The seats property</summary>
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Seats.SeatsRequestBuilder Seats
        {
            get => new global::SyncUp.ClickUp.Api.V2.Team.Item.Seats.SeatsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shared property</summary>
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Shared.SharedRequestBuilder Shared
        {
            get => new global::SyncUp.ClickUp.Api.V2.Team.Item.Shared.SharedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The space property</summary>
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpaceRequestBuilder Space
        {
            get => new global::SyncUp.ClickUp.Api.V2.Team.Item.Space.SpaceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The task property</summary>
        public global::SyncUp.ClickUp.Api.V2.Team.Item.TaskNamespace.TaskRequestBuilder Task
        {
            get => new global::SyncUp.ClickUp.Api.V2.Team.Item.TaskNamespace.TaskRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The taskTemplate property</summary>
        public global::SyncUp.ClickUp.Api.V2.Team.Item.TaskTemplate.TaskTemplateRequestBuilder TaskTemplate
        {
            get => new global::SyncUp.ClickUp.Api.V2.Team.Item.TaskTemplate.TaskTemplateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The time_entries property</summary>
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Time_entries.Time_entriesRequestBuilder Time_entries
        {
            get => new global::SyncUp.ClickUp.Api.V2.Team.Item.Time_entries.Time_entriesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::SyncUp.ClickUp.Api.V2.Team.Item.User.UserRequestBuilder User
        {
            get => new global::SyncUp.ClickUp.Api.V2.Team.Item.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The view property</summary>
        public global::SyncUp.ClickUp.Api.V2.Team.Item.View.ViewRequestBuilder View
        {
            get => new global::SyncUp.ClickUp.Api.V2.Team.Item.View.ViewRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhook property</summary>
        public global::SyncUp.ClickUp.Api.V2.Team.Item.Webhook.WebhookRequestBuilder Webhook
        {
            get => new global::SyncUp.ClickUp.Api.V2.Team.Item.Webhook.WebhookRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.Team.Item.Team_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Team_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/team/{team_%2Did}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.Team.Item.Team_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Team_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/team/{team_%2Did}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
