// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\task\{task_id}\checklist
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChecklistRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChecklistRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/task/{task_id}/checklist{?custom_task_ids*,team_id*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChecklistRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/task/{task_id}/checklist{?custom_task_ids*,team_id*}", rawUrl)
        {
        }
        /// <summary>
        /// Add a new checklist to a task.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistPostResponse?> PostAsChecklistPostResponseAsync(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistPostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistRequestBuilder.ChecklistRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistPostResponse> PostAsChecklistPostResponseAsync(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistPostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistRequestBuilder.ChecklistRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistPostResponse>(requestInfo, global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistPostResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Add a new checklist to a task.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PostAsChecklistPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistResponse?> PostAsync(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistPostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistRequestBuilder.ChecklistRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistResponse> PostAsync(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistPostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistRequestBuilder.ChecklistRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistResponse>(requestInfo, global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Add a new checklist to a task.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistPostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistRequestBuilder.ChecklistRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistPostRequestBody body, Action<RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistRequestBuilder.ChecklistRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Add a new checklist to a task.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChecklistRequestBuilderPostQueryParameters 
        {
            /// <summary>If you want to reference a task by it&apos;s custom task id, this value must be `true`.</summary>
            [QueryParameter("custom_task_ids")]
            public bool? CustomTaskIds { get; set; }
            /// <summary>When the `custom_task_ids` parameter is set to `true`, the Workspace ID must be provided using the `team_id` parameter. \For example: `custom_task_ids=true&amp;team_id=123`.</summary>
            [QueryParameter("team_id")]
            public double? TeamId { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ChecklistRequestBuilderPostRequestConfiguration : RequestConfiguration<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Checklist.ChecklistRequestBuilder.ChecklistRequestBuilderPostQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
