// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Member
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MemberGetResponse_members_profileInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The display_profile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayProfile { get; set; }
#nullable restore
#else
        public string DisplayProfile { get; set; }
#endif
        /// <summary>The top_tier_user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TopTierUser { get; set; }
#nullable restore
#else
        public string TopTierUser { get; set; }
#endif
        /// <summary>The verified_ambassador property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VerifiedAmbassador { get; set; }
#nullable restore
#else
        public string VerifiedAmbassador { get; set; }
#endif
        /// <summary>The verified_consultant property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VerifiedConsultant { get; set; }
#nullable restore
#else
        public string VerifiedConsultant { get; set; }
#endif
        /// <summary>The viewed_top_tier_user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ViewedTopTierUser { get; set; }
#nullable restore
#else
        public string ViewedTopTierUser { get; set; }
#endif
        /// <summary>The viewed_verified_ambassador property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ViewedVerifiedAmbassador { get; set; }
#nullable restore
#else
        public string ViewedVerifiedAmbassador { get; set; }
#endif
        /// <summary>The viewed_verified_consultant property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ViewedVerifiedConsultant { get; set; }
#nullable restore
#else
        public string ViewedVerifiedConsultant { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Member.MemberGetResponse_members_profileInfo"/> and sets the default values.
        /// </summary>
        public MemberGetResponse_members_profileInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Member.MemberGetResponse_members_profileInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Member.MemberGetResponse_members_profileInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.Member.MemberGetResponse_members_profileInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "display_profile", n => { DisplayProfile = n.GetStringValue(); } },
                { "top_tier_user", n => { TopTierUser = n.GetStringValue(); } },
                { "verified_ambassador", n => { VerifiedAmbassador = n.GetStringValue(); } },
                { "verified_consultant", n => { VerifiedConsultant = n.GetStringValue(); } },
                { "viewed_top_tier_user", n => { ViewedTopTierUser = n.GetStringValue(); } },
                { "viewed_verified_ambassador", n => { ViewedVerifiedAmbassador = n.GetStringValue(); } },
                { "viewed_verified_consultant", n => { ViewedVerifiedConsultant = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("display_profile", DisplayProfile);
            writer.WriteStringValue("top_tier_user", TopTierUser);
            writer.WriteStringValue("verified_ambassador", VerifiedAmbassador);
            writer.WriteStringValue("verified_consultant", VerifiedConsultant);
            writer.WriteStringValue("viewed_top_tier_user", ViewedTopTierUser);
            writer.WriteStringValue("viewed_verified_ambassador", ViewedVerifiedAmbassador);
            writer.WriteStringValue("viewed_verified_consultant", ViewedVerifiedConsultant);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
