// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\space\{space_id}\tag\{tag_name}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTag_nameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTag_nameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/space/{space_id}/tag/{tag_name}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTag_nameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/space/{space_id}/tag/{tag_name}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a task Tag from a Space.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameDeleteResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameDeleteResponse?> DeleteAsWithTag_nameDeleteResponseAsync(global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameDeleteRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameDeleteResponse> DeleteAsWithTag_nameDeleteResponseAsync(global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameDeleteRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToDeleteRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameDeleteResponse>(requestInfo, global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameDeleteResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a task Tag from a Space.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use DeleteAsWithTag_nameDeleteResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameResponse?> DeleteAsync(global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameDeleteRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameResponse> DeleteAsync(global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameDeleteRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToDeleteRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameResponse>(requestInfo, global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a task Tag.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_namePutResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_namePutResponse?> PutAsWithTag_namePutResponseAsync(global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_namePutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_namePutResponse> PutAsWithTag_namePutResponseAsync(global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_namePutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_namePutResponse>(requestInfo, global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_namePutResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update a task Tag.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use PutAsWithTag_namePutResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameResponse?> PutAsync(global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_namePutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameResponse> PutAsync(global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_namePutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameResponse>(requestInfo, global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a task Tag from a Space.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameDeleteRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameDeleteRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Update a task Tag.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_namePutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_namePutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::SyncUp.ClickUp.Api.V2.Space.Item.Tag.Item.WithTag_nameItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithTag_nameItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithTag_nameItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
