// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SyncUp.ClickUp.Api.V2.TaskNamespace.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithTask_GetResponse_attachments : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The date property</summary>
        public long? Date { get; set; }
        /// <summary>The deleted property</summary>
        public bool? Deleted { get; set; }
        /// <summary>The email_data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.WithTask_GetResponse_attachments_email_data? EmailData { get; set; }
#nullable restore
#else
        public global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.WithTask_GetResponse_attachments_email_data EmailData { get; set; }
#endif
        /// <summary>The extension property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Extension { get; set; }
#nullable restore
#else
        public string Extension { get; set; }
#endif
        /// <summary>The hidden property</summary>
        public bool? Hidden { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The is_folder property</summary>
        public bool? IsFolder { get; set; }
        /// <summary>The mimetype property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mimetype { get; set; }
#nullable restore
#else
        public string Mimetype { get; set; }
#endif
        /// <summary>The orientation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Orientation { get; set; }
#nullable restore
#else
        public string Orientation { get; set; }
#endif
        /// <summary>The parent_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentId { get; set; }
#nullable restore
#else
        public string ParentId { get; set; }
#endif
        /// <summary>The resolved_comments property</summary>
        public int? ResolvedComments { get; set; }
        /// <summary>The size property</summary>
        public long? Size { get; set; }
        /// <summary>The source property</summary>
        public int? Source { get; set; }
        /// <summary>The thumbnail_large property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThumbnailLarge { get; set; }
#nullable restore
#else
        public string ThumbnailLarge { get; set; }
#endif
        /// <summary>The thumbnail_medium property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThumbnailMedium { get; set; }
#nullable restore
#else
        public string ThumbnailMedium { get; set; }
#endif
        /// <summary>The thumbnail_small property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThumbnailSmall { get; set; }
#nullable restore
#else
        public string ThumbnailSmall { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The total_comments property</summary>
        public int? TotalComments { get; set; }
        /// <summary>The type property</summary>
        public int? Type { get; set; }
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>The url_w_host property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UrlWHost { get; set; }
#nullable restore
#else
        public string UrlWHost { get; set; }
#endif
        /// <summary>The url_w_query property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UrlWQuery { get; set; }
#nullable restore
#else
        public string UrlWQuery { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? User { get; set; }
#nullable restore
#else
        public UntypedNode User { get; set; }
#endif
        /// <summary>The version property</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.WithTask_GetResponse_attachments"/> and sets the default values.
        /// </summary>
        public WithTask_GetResponse_attachments()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.WithTask_GetResponse_attachments"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.WithTask_GetResponse_attachments CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.WithTask_GetResponse_attachments();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "date", n => { Date = n.GetLongValue(); } },
                { "deleted", n => { Deleted = n.GetBoolValue(); } },
                { "email_data", n => { EmailData = n.GetObjectValue<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.WithTask_GetResponse_attachments_email_data>(global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.WithTask_GetResponse_attachments_email_data.CreateFromDiscriminatorValue); } },
                { "extension", n => { Extension = n.GetStringValue(); } },
                { "hidden", n => { Hidden = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_folder", n => { IsFolder = n.GetBoolValue(); } },
                { "mimetype", n => { Mimetype = n.GetStringValue(); } },
                { "orientation", n => { Orientation = n.GetStringValue(); } },
                { "parent_id", n => { ParentId = n.GetStringValue(); } },
                { "resolved_comments", n => { ResolvedComments = n.GetIntValue(); } },
                { "size", n => { Size = n.GetLongValue(); } },
                { "source", n => { Source = n.GetIntValue(); } },
                { "thumbnail_large", n => { ThumbnailLarge = n.GetStringValue(); } },
                { "thumbnail_medium", n => { ThumbnailMedium = n.GetStringValue(); } },
                { "thumbnail_small", n => { ThumbnailSmall = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "total_comments", n => { TotalComments = n.GetIntValue(); } },
                { "type", n => { Type = n.GetIntValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "url_w_host", n => { UrlWHost = n.GetStringValue(); } },
                { "url_w_query", n => { UrlWQuery = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("date", Date);
            writer.WriteBoolValue("deleted", Deleted);
            writer.WriteObjectValue<global::SyncUp.ClickUp.Api.V2.TaskNamespace.Item.WithTask_GetResponse_attachments_email_data>("email_data", EmailData);
            writer.WriteStringValue("extension", Extension);
            writer.WriteBoolValue("hidden", Hidden);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("is_folder", IsFolder);
            writer.WriteStringValue("mimetype", Mimetype);
            writer.WriteStringValue("orientation", Orientation);
            writer.WriteStringValue("parent_id", ParentId);
            writer.WriteIntValue("resolved_comments", ResolvedComments);
            writer.WriteLongValue("size", Size);
            writer.WriteIntValue("source", Source);
            writer.WriteStringValue("thumbnail_large", ThumbnailLarge);
            writer.WriteStringValue("thumbnail_medium", ThumbnailMedium);
            writer.WriteStringValue("thumbnail_small", ThumbnailSmall);
            writer.WriteStringValue("title", Title);
            writer.WriteIntValue("total_comments", TotalComments);
            writer.WriteIntValue("type", Type);
            writer.WriteStringValue("url", Url);
            writer.WriteStringValue("url_w_host", UrlWHost);
            writer.WriteStringValue("url_w_query", UrlWQuery);
            writer.WriteObjectValue<UntypedNode>("user", User);
            writer.WriteIntValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
