// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ClickUp.Api.V2.TaskNamespace.Item.Guest.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithGuest_PostResponse_guest_shared_tasks : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The archived property</summary>
        public bool? Archived { get; set; }
        /// <summary>The assignees property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Assignees { get; set; }
#nullable restore
#else
        public List<string> Assignees { get; set; }
#endif
        /// <summary>The checklists property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Checklists { get; set; }
#nullable restore
#else
        public List<string> Checklists { get; set; }
#endif
        /// <summary>The creator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Creator { get; set; }
#nullable restore
#else
        public UntypedNode Creator { get; set; }
#endif
        /// <summary>The custom_fields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CustomFields { get; set; }
#nullable restore
#else
        public List<string> CustomFields { get; set; }
#endif
        /// <summary>The date_closed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateClosed { get; set; }
#nullable restore
#else
        public string DateClosed { get; set; }
#endif
        /// <summary>The date_created property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateCreated { get; set; }
#nullable restore
#else
        public string DateCreated { get; set; }
#endif
        /// <summary>The date_updated property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DateUpdated { get; set; }
#nullable restore
#else
        public string DateUpdated { get; set; }
#endif
        /// <summary>The dependencies property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Dependencies { get; set; }
#nullable restore
#else
        public List<string> Dependencies { get; set; }
#endif
        /// <summary>The due_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DueDate { get; set; }
#nullable restore
#else
        public string DueDate { get; set; }
#endif
        /// <summary>The folder property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Folder { get; set; }
#nullable restore
#else
        public UntypedNode Folder { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The list property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? List { get; set; }
#nullable restore
#else
        public UntypedNode List { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The orderindex property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Orderindex { get; set; }
#nullable restore
#else
        public string Orderindex { get; set; }
#endif
        /// <summary>The parent property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Parent { get; set; }
#nullable restore
#else
        public string Parent { get; set; }
#endif
        /// <summary>The permission_level property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PermissionLevel { get; set; }
#nullable restore
#else
        public string PermissionLevel { get; set; }
#endif
        /// <summary>The points property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Points { get; set; }
#nullable restore
#else
        public string Points { get; set; }
#endif
        /// <summary>The priority property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Priority { get; set; }
#nullable restore
#else
        public UntypedNode Priority { get; set; }
#endif
        /// <summary>The space property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Space { get; set; }
#nullable restore
#else
        public UntypedNode Space { get; set; }
#endif
        /// <summary>The start_date property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartDate { get; set; }
#nullable restore
#else
        public string StartDate { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Status { get; set; }
#nullable restore
#else
        public UntypedNode Status { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The team_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamId { get; set; }
#nullable restore
#else
        public string TeamId { get; set; }
#endif
        /// <summary>The time_estimate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeEstimate { get; set; }
#nullable restore
#else
        public string TimeEstimate { get; set; }
#endif
        /// <summary>The url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ClickUp.Api.V2.TaskNamespace.Item.Guest.Item.WithGuest_PostResponse_guest_shared_tasks"/> and sets the default values.
        /// </summary>
        public WithGuest_PostResponse_guest_shared_tasks()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ClickUp.Api.V2.TaskNamespace.Item.Guest.Item.WithGuest_PostResponse_guest_shared_tasks"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ClickUp.Api.V2.TaskNamespace.Item.Guest.Item.WithGuest_PostResponse_guest_shared_tasks CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ClickUp.Api.V2.TaskNamespace.Item.Guest.Item.WithGuest_PostResponse_guest_shared_tasks();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "assignees", n => { Assignees = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "checklists", n => { Checklists = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "creator", n => { Creator = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "date_closed", n => { DateClosed = n.GetStringValue(); } },
                { "date_created", n => { DateCreated = n.GetStringValue(); } },
                { "date_updated", n => { DateUpdated = n.GetStringValue(); } },
                { "dependencies", n => { Dependencies = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "due_date", n => { DueDate = n.GetStringValue(); } },
                { "folder", n => { Folder = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "list", n => { List = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "orderindex", n => { Orderindex = n.GetStringValue(); } },
                { "parent", n => { Parent = n.GetStringValue(); } },
                { "permission_level", n => { PermissionLevel = n.GetStringValue(); } },
                { "points", n => { Points = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "space", n => { Space = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "start_date", n => { StartDate = n.GetStringValue(); } },
                { "status", n => { Status = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "team_id", n => { TeamId = n.GetStringValue(); } },
                { "time_estimate", n => { TimeEstimate = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("archived", Archived);
            writer.WriteCollectionOfPrimitiveValues<string>("assignees", Assignees);
            writer.WriteCollectionOfPrimitiveValues<string>("checklists", Checklists);
            writer.WriteObjectValue<UntypedNode>("creator", Creator);
            writer.WriteCollectionOfPrimitiveValues<string>("custom_fields", CustomFields);
            writer.WriteStringValue("date_closed", DateClosed);
            writer.WriteStringValue("date_created", DateCreated);
            writer.WriteStringValue("date_updated", DateUpdated);
            writer.WriteCollectionOfPrimitiveValues<string>("dependencies", Dependencies);
            writer.WriteStringValue("due_date", DueDate);
            writer.WriteObjectValue<UntypedNode>("folder", Folder);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<UntypedNode>("list", List);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("orderindex", Orderindex);
            writer.WriteStringValue("parent", Parent);
            writer.WriteStringValue("permission_level", PermissionLevel);
            writer.WriteStringValue("points", Points);
            writer.WriteObjectValue<UntypedNode>("priority", Priority);
            writer.WriteObjectValue<UntypedNode>("space", Space);
            writer.WriteStringValue("start_date", StartDate);
            writer.WriteObjectValue<UntypedNode>("status", Status);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteStringValue("team_id", TeamId);
            writer.WriteStringValue("time_estimate", TimeEstimate);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
