// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace ClickUp.Api.V2.Team.Item.Goal
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GoalGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The folders property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ClickUp.Api.V2.Team.Item.Goal.GoalGetResponse_folders>? Folders { get; set; }
#nullable restore
#else
        public List<global::ClickUp.Api.V2.Team.Item.Goal.GoalGetResponse_folders> Folders { get; set; }
#endif
        /// <summary>The goals property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::ClickUp.Api.V2.Team.Item.Goal.GoalGetResponse_goals>? Goals { get; set; }
#nullable restore
#else
        public List<global::ClickUp.Api.V2.Team.Item.Goal.GoalGetResponse_goals> Goals { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::ClickUp.Api.V2.Team.Item.Goal.GoalGetResponse"/> and sets the default values.
        /// </summary>
        public GoalGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::ClickUp.Api.V2.Team.Item.Goal.GoalGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::ClickUp.Api.V2.Team.Item.Goal.GoalGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::ClickUp.Api.V2.Team.Item.Goal.GoalGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "folders", n => { Folders = n.GetCollectionOfObjectValues<global::ClickUp.Api.V2.Team.Item.Goal.GoalGetResponse_folders>(global::ClickUp.Api.V2.Team.Item.Goal.GoalGetResponse_folders.CreateFromDiscriminatorValue)?.AsList(); } },
                { "goals", n => { Goals = n.GetCollectionOfObjectValues<global::ClickUp.Api.V2.Team.Item.Goal.GoalGetResponse_goals>(global::ClickUp.Api.V2.Team.Item.Goal.GoalGetResponse_goals.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::ClickUp.Api.V2.Team.Item.Goal.GoalGetResponse_folders>("folders", Folders);
            writer.WriteCollectionOfObjectValues<global::ClickUp.Api.V2.Team.Item.Goal.GoalGetResponse_goals>("goals", Goals);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
