// <auto-generated/>
#pragma warning disable CS0618
using SyncUp.ClickUp.Api.V2.Goal.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SyncUp.ClickUp.Api.V2.Goal
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\goal
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GoalRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the SyncUp.ClickUp.Api.v2.goal.item collection</summary>
        /// <param name="position">900e-462d-a849-4a216b06d930 (uuid)</param>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.Goal.Item.WithGoal_ItemRequestBuilder"/></returns>
        public global::SyncUp.ClickUp.Api.V2.Goal.Item.WithGoal_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("goal_id", position);
                return new global::SyncUp.ClickUp.Api.V2.Goal.Item.WithGoal_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.Goal.GoalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GoalRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/goal", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.Goal.GoalRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GoalRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/goal", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
