// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace SyncUp.ClickUp.Api.V2.Checklist.Item.Checklist_item.Item
{
    [Obsolete("This class is obsolete. Use WithChecklist_item_PutResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithChecklist_item_Response : global::SyncUp.ClickUp.Api.V2.Checklist.Item.Checklist_item.Item.WithChecklist_item_PutResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.Checklist.Item.Checklist_item.Item.WithChecklist_item_Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::SyncUp.ClickUp.Api.V2.Checklist.Item.Checklist_item.Item.WithChecklist_item_Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::SyncUp.ClickUp.Api.V2.Checklist.Item.Checklist_item.Item.WithChecklist_item_Response();
        }
    }
}
#pragma warning restore CS0618
