// <auto-generated/>
#pragma warning disable CS0618
using SyncUp.ClickUp.Api.V2.Checklist.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace SyncUp.ClickUp.Api.V2.Checklist
{
    /// <summary>
    /// Builds and executes requests for operations under \v2\checklist
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChecklistRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the SyncUp.ClickUp.Api.v2.checklist.item collection</summary>
        /// <param name="position">b8a8-48d8-a0c6-b4200788a683 (uuid)</param>
        /// <returns>A <see cref="global::SyncUp.ClickUp.Api.V2.Checklist.Item.WithChecklist_ItemRequestBuilder"/></returns>
        public global::SyncUp.ClickUp.Api.V2.Checklist.Item.WithChecklist_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("checklist_id", position);
                return new global::SyncUp.ClickUp.Api.V2.Checklist.Item.WithChecklist_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.Checklist.ChecklistRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChecklistRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/checklist", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::SyncUp.ClickUp.Api.V2.Checklist.ChecklistRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChecklistRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v2/checklist", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
